[package]
name = "gemini"
version = "0.1.0"
edition = "2021"

[dependencies]
gemini-api = { path = "../gemini-api", features = ["blocking"]}
ratatui ={ workspace = true }
anyhow = { workspace = true }
