name: Release By Zigbuild

permissions:
  "contents": "write"

on:
  pull_request:
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build-all:    
    strategy:
      matrix:
        target: 
          - "aarch64-apple-darwin" 
          - "x86_64-apple-darwin"
          - "x86_64-unknown-linux-gnu"
          - "aarch64-unknown-linux-gnu"
          - "x86_64-pc-windows-msvc"
    name: Build For ${{ matrix.target }}
    uses: ./.github/workflows/zigbuild.yml
    with:
      target: ${{ matrix.target }}

  read-changelog:
    runs-on: ubuntu-latest
    needs: build-all
    outputs:
      title: ${{ steps.read.outputs.title }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: read CHANGELOG.md to outputs
        id: read
        run: |
          echo "title=$(awk '/^#[^#]/{sub(/^# /, ""); print; exit}' CHANGELOG.md)" >> "$GITHUB_OUTPUT"
          echo "$(awk '/^#[^#]/{if (flag) exit; flag=1; next} flag {if ($0 ~ /\S/) {print; found=1} else if (found) {print}}' CHANGELOG.md)" > body.txt
      - name: Upload changelog body
        uses: actions/upload-artifact@v4
        with:
          name: body
          path: ./body.txt

  release:
    runs-on: ubuntu-latest
    needs: read-changelog
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: product
          pattern: gemini-*
          merge-multiple: false
      - name: Download Changelog Body
        uses: actions/download-artifact@v4
        with:
          path: product
          pattern: body
          merge-multiple: true
      - name: compress
        run: |
          for dir in product/*/; do
            zip -r "${dir%/}.zip" "$dir"
          done
      - name: List Directory
        run: ls -R product
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ needs.read-changelog.outputs.title }}
          body_path: ./product/body.txt
          draft: false
          fail_on_unmatched_files: true
          prerelease: false
          files: ./product/*.zip
